= {Title}
:title:     pdftools
:author:    Urs Roesch
:firstname: Urs
:lastname:  Roesch
:email:     github@bun.ch
:revnumber: 0.7.0
:keywords:  PDF, CLI, Command Line, tools, documents, pdftk, ghostscript, tesseract, OCR
:icons:     font
:!toc:

A collection of PDF command line tools and wrappers for Linux


[[img2pdf]]
== img2pdf

A script to convert PNGs, TIFFs or JPEGs to PDF files.

License:: MIT
Requires:: bash, pdfcat, ImageMagick, pdftk

[[img2-usage]]
=== Usage

----
img2pdf <options> <img-file> [<img-file> ... ]

Options:
  -h  | --help           This message
  -d  | --delete         Delete the images after creating the PDF file.
  -o  | --output <name>  Write the output to specified file <name>.
                         Implies -s
  -r  | --rotate <value> Rotate the image by <value>
                         Where value can be a positive or negative integer
                         between 0 and 360.
----

[[img2pdf-examples]]
=== Examples

.Create single page pdfs from images
----
img2pdf first.png second.jpg
----

.Create single page pdfs from images and then delete the original images.
----
img2pdf --delete first.png second.jpg
----

.Rotate the image 180 degress prior to creating the pdf
----
img2pdf --rotate 180 myimage.png
----

.Rotate the images by 180 degress and concatenate everyting into file `output.pdf`
----
img2pdf --output output.pdf --rotate 180 page1.png page2.jpg
----

<<<

[[ocrpdf]]
== ocrpdf

Runs PDFs through OCR and saves the output as a text searchable PDF
with the same name.

NOTE: Only works with quality degradation for PDFs comprised of a single
      JPEG, LZW or deflated image per page.
      LZW compressed images will be converted to deflated ones during
      the OCR process but there is no loss of fidelity.
      Composite images with multiple layers as JBIG2, CCITT or SMASKS
      are rendered as a flat image before running through OCR. The
      resulting PDFs are suffixed with '-ocrpdf.pdf' preserving the
      original file.


License:: MIT
Requires:: bash, pdfcat, pdftk, tesseract,
  pdfimages (poppler-utils), pdftocairo (poppler-utils)

[[ocrpdf-usage]]
=== Usage

----
ocrpdf [options] <file> [<file> [,,]]

Options:
  -R | --render <img>  Render composite images as either png or jpeg before
                       running through OCR.
                       default: png
  -h | --help          This message
  -v | --version       Print version information and exit
  -l | --lang          Set the OCR language for multiple concatenate with a +
                       E.g eng+deu for English and German
                       default: osd+ita+deu+equ+fra+eng+jpn
----

[[ocrpdf-exmples]]
=== Examples

.Run OCR with all installed languages on a couple of PDFs
----
ocrpdf first.pdf second.pdf
----

.Run OCR with German dictionary on a single PDF
----
ocrpdf --lang deu german.pdf
----

.Run OCR with German, French and English dictionaries on multiple PDFs
----
ocrpdf --lang deu+fra+eng  scanned_*.pdf
----

.Convert compsite images to JPEG before running running through OCR
----
ocrpdf --render jpeg scanned_document.pdf
----

<<<

[[pdfcat]]
== pdfcat

A quick hack to replace `pdfunite` as it destroys too much of the original's
meta data.

License:: MIT
Requires:: bash, pdftk >= 2.0

[[pdfcat-usage]]
=== Usage

----
pdfcat <pdf> <pdf> [..]
----

[[pdfcat-exmples]]
=== Examples

.Merging two PDFs into a new one
----
pdfcat first.pdf  second.pdf > merged.pdf
----

.Merging sequentially ordered pdfs into a single document
----
pdfcat myscan*.pdf > merged.pdf
----

<<<

[[pdfmeta]]
== pdfmeta

A wrapper script around `pdftk` to manipulate a PDFs meta data

License:: MIT
Requires:: bash >= 4.0, pdftk >= 2.0

[[pdfmeta-usage]]
=== Usage

----
pdfmeta <options> <pdf> [[<pdf>] ..]

Options:
  -h | --help               This message
  -k | --keywords           Comma seperated list of keywords
  -s | --subject            Define the PDFs subject
  -t | --title              Define the PDFs title
  -c | --creator            Define the PDFs creator program or library
  -p | --producer           Define the PDFs producing program
  -C | --creation-date      Set the creation date of the PDF
  -M | --modification-date  Set the modification date of the PDF
----

[[pdfmeta-examples]]
=== Examples

.Modify keywords
----
pdfmeta --keywords "rainbow, magical, unicorn" unicorn.pdf rainbow.pdf
----

.Modify creation date
----
pdfmeta --creation-date "2017-01-01 22:30:45" unicorn.pdf
----

<<<

[[pdfresize]]
== pdfresize

A wrapper aroung `ghostscript` to reduce the size of a scanned document

NOTE: pdfresize is very likely not working with PDF documents containing
https://en.wikipedia.org/wiki/JBIG2[JBIG2] images

License:: MIT
Requires:: bash, ghostscript

[[pdfresize-usage]]
=== Usage

----
Usage: pdfresize [pdfsettings] <input> <output>

  <input>      A PDF file preferably of high resolution
  <output>     Name of the PDF file to save the result to
  pdfsettings
    screen   - low-resolution; comparable to "Screen Optimized" in Acrobat Distiller
    ebook    - medium-resolution; comparable to "eBook" in Acrobat Distiller
    printer  - comparable to "Print Optimized" in Acrobat Distiller
    prepress - comparable to "Prepress Optimized" in Acrobat Distiller
    default  - intended to be useful across a wide variety of uses
----

[[pdfresize-examples]]
=== Examples

.Resize to default resolution
----
pdresize input.pdf output.pdf
----

.Resize to sreen resolution
----
pdfresize screen input.pdf output.pdf
----

[[pdf2pdfa]]
== pdf2pdfa 

Small script to convert a PDF to PDF/A type. 

NOTE: This is early beta and all the meta data in the PDF will be lost!

[[pdf2pdfa-usage]]
== Usage 

-----
  Usage:
    pdf2pdfa [-h] [-s <suffix>] <pdf_file> [<pdf_file> [..]]

  Options:
    -h | --help             This message
    -s | --suffix <suffix>  Append <suffix> to filename
                            Default '_a'
-----

[[pdfresize-examples]]
=== Examples

.Convert a pdf file `sample.pdf` to a PDF/A called `sample_a.pdf`
----
pdf2pdfa sample.pdf
----

.Convert a pdf file `sample.pdf` to a PDF/A called `sample_pdfa.pdf`
----
pdf2pdfa --suffix _pdfa sample.pdf
----
