= {Title}
:title:     pdftools
:author:    Urs Roesch
:firstname: Urs
:lastname:  Roesch
:email:     github@bun.ch
:revnumber: 0.7.0
:keywords:  PDF, CLI, Command Line, tools, documents, pdftk, ghostscript, tesseract, OCR
:!toc:

A collection of PDF command line tools and wrappers for Linux


[[img2pdf]]
== img2pdf

A script to convert PNGs, TIFFs or JPEGs to PDF files.

License:: MIT
Requires:: bash, pdfcat, ImageMagick, pdftk

[[img2-usage]]
=== Usage

----
  Usage:
    img2pdf <options> <img-file> [<img-file> ... ]

  Options:
    -h  | --help           This message
    -d  | --delete         Delete the images after creating the PDF file.
    -o  | --output <name>  Write the output to specified file <name>.
    -r  | --rotate <value> Rotate the image by <value>
                           Where value can be a positive or negative integer
                           between 0 and 360.
    -V  | --version        Display version and exit

----

[[img2pdf-examples]]
=== Examples

.Create single page pdfs from images
----
img2pdf first.png second.jpg
----

.Create single page pdfs from images and then delete the original images.
----
img2pdf --delete first.png second.jpg
----

.Rotate the image 180 degress prior to creating the pdf
----
img2pdf --rotate 180 myimage.png
----

.Rotate the images by 180 degress and concatenate everyting into file `output.pdf`
----
img2pdf --output output.pdf --rotate 180 page1.png page2.jpg
----

<<<

[[ocrpdf]]
== ocrpdf

Runs PDFs through OCR and saves the output as a text searchable PDF
with the same name.

NOTE: Only works with PDFs comprised of a single JPEG, LZW or ZIP compressed
image per page. LZW compressed images are being converted to ZIP compressed
one during the OCR process.

License:: MIT
Requires:: bash, pdfcat, pdfimages (poppler-utils), pdftk, tesseract

[[ocrpdf-usage]]
=== Usage

----
  Usage:
    ocrpdf [options] <file> [<file> [,,]]

  Options:
    -h | --help         This message
    -q | --quiet        Don't send display processed file names
    -V | --version      Print version information and exit
    -l | --lang <lang>  Set the OCR languages to use.
                        For multiple languages concatenate with a '+'
                        E.g eng+deu for English and German
                        Default: deu+eng+fra+ita+jpn+osd

  Description:
    Runs PDFs through OCR and saves the output as a text searchable PDF
    with the same name.

  Disclaimer:
    Only works with PDFs comprised of a single JPEG, LZW or ZIP compressed
    image per page.
    LZW compressed images will be converted to ZIP compressed ones during
    the OCR process.
----

[[ocrpdf-exmples]]
=== Examples

.Run OCR with all installed languages on a couple of PDFs
----
ocrpdf first.pdf second.pdf
----

.Run OCR with German dictionary on a single PDF
----
ocrpdf --lang deu german.pdf
----

.Run OCR with German, French and English dictionaries on multiple PDFs
----
ocrpdf --lang deu+fra+eng  scanned_*.pdf
----

<<<

[[pdfcat]]
== pdfcat

A quick hack to replace `pdfunite` as it destroys too much of the original's
meta data.

License:: MIT
Requires:: bash, pdftk >= 2.0

[[pdfcat-usage]]
=== Usage

----
pdfcat <pdf> <pdf> [..]
----

[[pdfcat-exmples]]
=== Examples

.Merging two PDFs into a new one
----
pdfcat first.pdf  second.pdf > merged.pdf
----

.Merging sequentially ordered pdfs into a single document
----
pdfcat myscan*.pdf > merged.pdf
----

<<<

[[pdfmeta]]
== pdfmeta

A wrapper script around `pdftk` to manipulate a PDFs meta data

License:: MIT
Requires:: bash >= 4.0, pdftk >= 2.0

[[pdfmeta-usage]]
=== Usage

----
  Usage:
    pdfmeta <options> <pdf> [[<pdf>] ..]

    Options:
      -h | --help               This message
      -k | --keywords           Comma seperated list of keywords
      -s | --subject            Define the PDFs subject
      -t | --title              Define the PDFs title
      -c | --creator            Define the PDFs creator program or library
      -p | --producer           Define the PDFs producing program
      -C | --creation-date      Set the creation date of the PDF
      -M | --modification-date  Set the modification date of the PDF
      -V | --version            Display version and exit
----

[[pdfmeta-examples]]
=== Examples

.Modify keywords
----
pdfmeta --keywords "rainbow, magical, unicorn" unicorn.pdf rainbow.pdf
----

.Modify creation date
----
pdfmeta --creation-date "2017-01-01 22:30:45" unicorn.pdf
----

<<<

[[pdfresize]]
== pdfresize

A wrapper aroung `ghostscript` to reduce the size of a scanned document

NOTE: pdfresize is very likely not working with PDF documents containing
https://en.wikipedia.org/wiki/JBIG2[JBIG2] images

License:: MIT
Requires:: bash, ghostscript

[[pdfresize-usage]]
=== Usage

----
  Usage: 
    pdfresize [-q pdfsettings] -i <input> -o <output>

  Options:
    -h | --help              This message
    -i | --input <input>     A PDF file preferably of high resolution
    -o | --output <output>   Name of the PDF file to save the result to
    -q | --quality <quality> Quality settings for output PDF.
                             See quality keywords for acceptable input.
    -V | --version           Print version and exit.

  Quality keywords:
    screen   - low-resolution; comparable to "Screen Optimized" in Acrobat Distiller
    ebook    - medium-resolution; comparable to "eBook" in Acrobat Distiller
    printer  - comparable to "Print Optimized" in Acrobat Distiller
    prepress - comparable to "Prepress Optimized" in Acrobat Distiller
    default  - intended to be useful across a wide variety of uses
----

[[pdfresize-examples]]
=== Examples

.Resize to default resolution
----
pdresize --input input.pdf --output output.pdf
----

.Resize to sreen resolution
----
pdfresize --quality screen --input input.pdf --output output.pdf
----

[[pdf2pdfa]]
== pdf2pdfa 

Small script to convert a PDF to PDF/A type. 

NOTE: This is early beta and all the meta data in the PDF will be lost!

[[pdf2pdfa-usage]]
== Usage 

-----
  Usage:
    pdf2pdfa [-h] [-s <suffix>] <pdf_file> [<pdf_file> [..]]

  Options:
    -h | --help             This message
    -s | --suffix <suffix>  Append <suffix> to filename
                            Default '_a'
-----

[[pdfresize-examples]]
=== Examples

.Convert a pdf file `sample.pdf` to a PDF/A called `sample_a.pdf`
----
pdf2pdfa sample.pdf
----

.Convert a pdf file `sample.pdf` to a PDF/A called `sample_pdfa.pdf`
----
pdf2pdfa --suffix _pdfa sample.pdf
----
