# -----------------------------------------------------------------------------
# Verify bash compatibility
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.2.0
# -----------------------------------------------------------------------------
name: bash-compatibility

on:
  push:
    branches:
    - workflow/*
  pull_request:
    branches:
    - master
    - main

jobs:
  bash-compatibility:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: bash:${{ matrix.bash }}
    strategy:
      fail-fast: false
      matrix:
        bash:
          - '4.0'
          - '4.1'
          - '4.2'
          - '4.3'
          - '4.4'
          - '5.0'
          - '5.1'
          - '5.2'
    env:
      PDFTK_URL: https://gitlab.com/pdftk-java/pdftk/-/package_files/53763921/download

    steps:
    - name: Install apk dependencies
      shell: bash
      run: |
        apk add \
          bats \
          curl \
          file \
          git \
          git-lfs \
          grep \
          imagemagick \
          make \
          openjdk11-jre-headless \
          poppler-utils \
          sane-utils \
          tesseract-ocr \
          tesseract-ocr-data-deu \
          tesseract-ocr-data-eng \
          tesseract-ocr-data-fra \
          tesseract-ocr-data-ita

    - name: Install pdftk
      shell: bash
      run: >
        curl -sJL -o /usr/lib/pdftk-all.jar "${PDFTK_URL}" &&
        printf "#!/usr/bin/env bash\njava -jar /usr/lib/pdftk-all.jar \"\$@\"" > /usr/bin/pdftk &&
        chmod 755 /usr/bin/pdftk

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Check bash compatibilty
      shell: bash
      run: make test
