# -----------------------------------------------------------------------------
# Build documents for pdftools
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.1.0 
# -----------------------------------------------------------------------------
name: create-docs

on:
  push:
    branches: 
    - workflow/*
  pull_request:
    branches:
    - master

jobs:
  create-docs:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-18.04

    steps:
    - name: Install asciidoctor 
      shell: bash
      run: >
        sudo gem install asciidoctor asciidoctor-pdf

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create documents
      shell: bash
      run: >
        make docs
