# -----------------------------------------------------------------------------
# Build documents for pdftools
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.1.2
# -----------------------------------------------------------------------------
name: create-docs

on:
  push:
    branches:
    - workflow/*
  pull_request:
    branches:
    - master
    - main

jobs:
  create-docs:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    strategy:
      matrix:
        container:
          - ubuntu:22.04
          - ubuntu:20.04
          - ubuntu:18.04
          - debian:11
          - debian:10
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
    - name: Install dependencies
      shell: bash
      run: |
        apt update
        apt install -y make sudo

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create documents
      shell: bash
      run: make docs
