# -----------------------------------------------------------------------------
# Test pdftools
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.3.0
# -----------------------------------------------------------------------------
name: os-compatibility

on:
  push:
    branches:
    - workflow/*
  pull_request:
    branches:
    - master
    - main

env:
  PDFTK_URL: https://gitlab.com/pdftk-java/pdftk/-/jobs/812582458/artifacts/raw/build/libs/pdftk-all.jar?inline=false 

jobs:
  debian:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.name }}:${{ matrix.release }}
    strategy:
      matrix:
        include:
          - { name: ubuntu, release: 22.04 }
          - { name: ubuntu, release: 20.04 }
          - { name: ubuntu, release: 18.04 }
        # - { name: ubuntu, release: 16.04 }
          - { name: debian, release: 11 }
          - { name: debian, release: 10 }
        
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
    - name: Install dependencies other than pdftk
      shell: bash
      run: >
        apt-get update;
        apt-get -y install
        bats
        curl
        file
        gawk
        ghostscript
        git
        imagemagick
        make
        poppler-utils
        sane-utils
        tesseract-ocr
        ;

    - name: Install pdftk on non Ubuntu 18.04
      if: matrix.release != '18.04'
      shell: bash
      run: apt-get -y install pdftk

    - name: Install pdftk on Ubuntu 18.04
      if: >
        matrix.name == 'ubuntu' &&
        matrix.release == '18.04'
      shell: bash
      run: |
         curl -sJL -o /usr/lib/pdftk-all.jar "${PDFTK_URL}" && \
         printf "%s\n" \
           '#!/usr/bin/env sh' \
           'java -cp /usr/lib/pdftk-all.jar com.gitlab.pdftk_java.pdftk "$@"' \
           > /usr/bin/pdftk
         chmod 755 /usr/bin/pdftk
         apt install -y openjdk-11-jre-headless

    - name: Adjust ImageMagick configuration
      shell: bash
      run: >
        test -f /etc/ImageMagick-6/policy.xml &&
        sed -i '/pattern="PDF"/s/rights="none"/rights="read\|write"/'
        /etc/ImageMagick-6/policy.xml

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Test pdftools functionality
      shell: bash
      run: |
        export PATH=${GITHUB_WORKSPACE}/bin:${PATH}
        make test


  redhat:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.name }}:${{ matrix.release }}
    strategy:
      matrix:
        include:
          #- { name: centos,     release: 7 }
          - { name: rockylinux, release: 8 }
          #- { name: rockylinux, release: 9 }
        
    steps:
    - name: Install dependencies other than pdftk
      shell: bash
      run: >
        yum -y install epel-release;
        yum -y --allowerasing install
        ImageMagick
        bats
        coreutils 
        curl
        file
        gawk
        ghostscript
        git
        java-11-openjdk-headless
        make
        poppler-utils
        sane-frontends
        tesseract
        ;

    - name: Install pdftk
      shell: bash
      run: |
         curl -sJL -o /usr/lib/pdftk-all.jar "${PDFTK_URL}" && \
         printf "%s\n" \
           '#!/usr/bin/env sh' \
           'java -cp /usr/lib/pdftk-all.jar com.gitlab.pdftk_java.pdftk "$@"' \
           > /usr/bin/pdftk
         chmod 755 /usr/bin/pdftk

    - name: Adjust ImageMagick configuration
      shell: bash
      run: >
        test -f /etc/ImageMagick-6/policy.xml &&
        sed -i '/pattern="PDF"/s/rights="none"/rights="read\|write"/'
        /etc/ImageMagick-6/policy.xml

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Test pdftools functionality
      shell: bash
      run: |
        export PATH=${GITHUB_WORKSPACE}/bin:${PATH}
        #bats tests/*bats
        make test
