# -----------------------------------------------------------------------------
# Test pdftools
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.2.2
# -----------------------------------------------------------------------------
name: test-pdftools

on:
  push:
    branches:
    - workflow/*
  pull_request:
    branches:
    - master
    - main

jobs:
  test-pdftools:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-22.04
        - ubuntu-20.04
        - ubuntu-18.04

    steps:
    - name: Install pdftk on Ubuntu 18.04
      if: matrix.os == 'ubuntu-18.04'
      shell: bash
      run: sudo snap install pdftk

    - name: Install pdftk on non Ubuntu 18.04
      if: matrix.os != 'ubuntu-18.04'
      shell: bash
      run: sudo apt-get -y install pdftk

    - name: Install dependencies other than pdftk
      shell: bash
      run: >
        sudo apt-get update;
        sudo apt-get -y install
        bats
        ghostscript
        imagemagick
        poppler-utils
        tesseract-ocr
        sane-utils
        ;

    - name: Adjust ImageMagick configuration
      shell: bash
      run: >
        test -f /etc/ImageMagick-6/policy.xml &&
        sudo sed -i '/pattern="PDF"/s/rights="none"/rights="read\|write"/'
        /etc/ImageMagick-6/policy.xml

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Test pdftools functionality
      shell: bash
      run: |
        export PATH=${GITHUB_WORKSPACE}/bin:${PATH}
        make test
